services:
  php:
    container_name: payment_php
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: payment_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    container_name: payment_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      
  symfony_cli:
    container_name: payment_symfony_cli
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - database
    tty: true
    stdin_open: true
    command: /bin/bash

volumes:
  db-data:
